// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type {
  DeleteApplicationsByAppIdData,
  DeleteApplicationsByAppIdErrors,
  DeleteApplicationsByAppIdResponses,
  DeleteSkillsBySkillIdData,
  DeleteSkillsBySkillIdErrors,
  DeleteSkillsBySkillIdResponses,
  DeleteTopicsByTopicIdData,
  DeleteTopicsByTopicIdErrors,
  DeleteTopicsByTopicIdFavoriteData,
  DeleteTopicsByTopicIdFavoriteErrors,
  DeleteTopicsByTopicIdFavoriteResponses,
  DeleteTopicsByTopicIdResponses,
  DeleteUsersByUserIdData,
  DeleteUsersByUserIdErrors,
  DeleteUsersByUserIdResponses,
  GetApplicationsByAppIdData,
  GetApplicationsByAppIdErrors,
  GetApplicationsByAppIdResponses,
  GetApplicationsData,
  GetApplicationsErrors,
  GetApplicationsResponses,
  GetDepartmentsData,
  GetDepartmentsErrors,
  GetDepartmentsResponses,
  GetSkillsData,
  GetSkillsErrors,
  GetSkillsResponses,
  GetTopicsByTopicIdData,
  GetTopicsByTopicIdErrors,
  GetTopicsByTopicIdResponses,
  GetTopicsData,
  GetTopicsErrors,
  GetTopicsResponses,
  GetUsersByUserIdData,
  GetUsersByUserIdErrors,
  GetUsersByUserIdResponses,
  GetUsersMeData,
  GetUsersMeErrors,
  GetUsersMeResponses,
  GetUsersMeSkillsData,
  GetUsersMeSkillsErrors,
  GetUsersMeSkillsResponses,
  PatchApplicationsByAppIdData,
  PatchApplicationsByAppIdErrors,
  PatchApplicationsByAppIdResponses,
  PatchSkillsBySkillIdData,
  PatchSkillsBySkillIdErrors,
  PatchSkillsBySkillIdResponses,
  PatchTopicsByTopicIdData,
  PatchTopicsByTopicIdErrors,
  PatchTopicsByTopicIdResponses,
  PatchUsersByUserIdData,
  PatchUsersByUserIdErrors,
  PatchUsersByUserIdResponses,
  PatchUsersByUserIdRoleData,
  PatchUsersByUserIdRoleErrors,
  PatchUsersByUserIdRoleResponses,
  PatchUsersMeData,
  PatchUsersMeErrors,
  PatchUsersMeResponses,
  PostApplicationsData,
  PostApplicationsErrors,
  PostApplicationsResponses,
  PostAuthLoginData,
  PostAuthLoginErrors,
  PostAuthLoginResponses,
  PostAuthRegisterData,
  PostAuthRegisterErrors,
  PostAuthRegisterResponses,
  PostSkillsData,
  PostSkillsErrors,
  PostSkillsResponses,
  PostTopicsByTopicIdFavoriteData,
  PostTopicsByTopicIdFavoriteErrors,
  PostTopicsByTopicIdFavoriteResponses,
  PostTopicsByTopicIdSkillsData,
  PostTopicsByTopicIdSkillsErrors,
  PostTopicsByTopicIdSkillsResponses,
  PostTopicsData,
  PostTopicsErrors,
  PostTopicsResponses,
  PostUsersMeSkillsData,
  PostUsersMeSkillsErrors,
  PostUsersMeSkillsResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Регистрация нового пользователя
 *
 * Создает пользователя с ролью по умолчанию 'student' и возвращает токен.
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostAuthRegisterData, ThrowOnError>
) =>
  (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Вход пользователя
 *
 * Возвращает JWT токен доступа.
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostAuthLoginData, ThrowOnError>
) =>
  (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });

/**
 * Получить профиль текущего пользователя
 */
export const getUsersMe = <ThrowOnError extends boolean = false>(options?: Options<GetUsersMeData, ThrowOnError>) =>
  (options?.client ?? client).get<GetUsersMeResponses, GetUsersMeErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
  });

/**
 * Обновить профиль текущего пользователя
 */
export const patchUsersMe = <ThrowOnError extends boolean = false>(options: Options<PatchUsersMeData, ThrowOnError>) =>
  (options.client ?? client).patch<PatchUsersMeResponses, PatchUsersMeErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить пользователя
 */
export const deleteUsersByUserId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUsersByUserIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteUsersByUserIdResponses, DeleteUsersByUserIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
  });

/**
 * Получить пользователя по ID
 */
export const getUsersByUserId = <ThrowOnError extends boolean = false>(
  options: Options<GetUsersByUserIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetUsersByUserIdResponses, GetUsersByUserIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
  });

/**
 * Обновить пользователя
 */
export const patchUsersByUserId = <ThrowOnError extends boolean = false>(
  options: Options<PatchUsersByUserIdData, ThrowOnError>
) =>
  (options.client ?? client).patch<PatchUsersByUserIdResponses, PatchUsersByUserIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Изменить роль пользователя
 */
export const patchUsersByUserIdRole = <ThrowOnError extends boolean = false>(
  options: Options<PatchUsersByUserIdRoleData, ThrowOnError>
) =>
  (options.client ?? client).patch<PatchUsersByUserIdRoleResponses, PatchUsersByUserIdRoleErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Получить список всех кафедр
 */
export const getDepartments = <ThrowOnError extends boolean = false>(
  options?: Options<GetDepartmentsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetDepartmentsResponses, GetDepartmentsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/departments',
    ...options,
  });

/**
 * Получить список тем
 */
export const getTopics = <ThrowOnError extends boolean = false>(options?: Options<GetTopicsData, ThrowOnError>) =>
  (options?.client ?? client).get<GetTopicsResponses, GetTopicsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics',
    ...options,
  });

/**
 * Создать тему
 */
export const postTopics = <ThrowOnError extends boolean = false>(options: Options<PostTopicsData, ThrowOnError>) =>
  (options.client ?? client).post<PostTopicsResponses, PostTopicsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить тему
 */
export const deleteTopicsByTopicId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTopicsByTopicIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteTopicsByTopicIdResponses, DeleteTopicsByTopicIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics/{topic_id}',
    ...options,
  });

/**
 * Получить детали темы
 */
export const getTopicsByTopicId = <ThrowOnError extends boolean = false>(
  options: Options<GetTopicsByTopicIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetTopicsByTopicIdResponses, GetTopicsByTopicIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics/{topic_id}',
    ...options,
  });

/**
 * Обновить тему
 */
export const patchTopicsByTopicId = <ThrowOnError extends boolean = false>(
  options: Options<PatchTopicsByTopicIdData, ThrowOnError>
) =>
  (options.client ?? client).patch<PatchTopicsByTopicIdResponses, PatchTopicsByTopicIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics/{topic_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Удалить из избранного
 */
export const deleteTopicsByTopicIdFavorite = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTopicsByTopicIdFavoriteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTopicsByTopicIdFavoriteResponses,
    DeleteTopicsByTopicIdFavoriteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics/{topic_id}/favorite',
    ...options,
  });

/**
 * Добавить тему в избранное
 */
export const postTopicsByTopicIdFavorite = <ThrowOnError extends boolean = false>(
  options: Options<PostTopicsByTopicIdFavoriteData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PostTopicsByTopicIdFavoriteResponses,
    PostTopicsByTopicIdFavoriteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics/{topic_id}/favorite',
    ...options,
  });

/**
 * Получить список всех навыков
 */
export const getSkills = <ThrowOnError extends boolean = false>(options?: Options<GetSkillsData, ThrowOnError>) =>
  (options?.client ?? client).get<GetSkillsResponses, GetSkillsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/skills',
    ...options,
  });

/**
 * Создать навык
 */
export const postSkills = <ThrowOnError extends boolean = false>(options?: Options<PostSkillsData, ThrowOnError>) =>
  (options?.client ?? client).post<PostSkillsResponses, PostSkillsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/skills',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Удалить навык
 */
export const deleteSkillsBySkillId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSkillsBySkillIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteSkillsBySkillIdResponses, DeleteSkillsBySkillIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/skills/{skill_id}',
    ...options,
  });

/**
 * Обновить навык
 */
export const patchSkillsBySkillId = <ThrowOnError extends boolean = false>(
  options: Options<PatchSkillsBySkillIdData, ThrowOnError>
) =>
  (options.client ?? client).patch<PatchSkillsBySkillIdResponses, PatchSkillsBySkillIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/skills/{skill_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Получить навыки текущего пользователя
 */
export const getUsersMeSkills = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersMeSkillsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetUsersMeSkillsResponses, GetUsersMeSkillsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/skills',
    ...options,
  });

/**
 * Добавить навык пользователю
 */
export const postUsersMeSkills = <ThrowOnError extends boolean = false>(
  options?: Options<PostUsersMeSkillsData, ThrowOnError>
) =>
  (options?.client ?? client).post<PostUsersMeSkillsResponses, PostUsersMeSkillsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/skills',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Добавить требуемый навык к теме
 */
export const postTopicsByTopicIdSkills = <ThrowOnError extends boolean = false>(
  options: Options<PostTopicsByTopicIdSkillsData, ThrowOnError>
) =>
  (options.client ?? client).post<PostTopicsByTopicIdSkillsResponses, PostTopicsByTopicIdSkillsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/topics/{topic_id}/skills',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Получить список заявок
 */
export const getApplications = <ThrowOnError extends boolean = false>(
  options?: Options<GetApplicationsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetApplicationsResponses, GetApplicationsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications',
    ...options,
  });

/**
 * Создать заявку на тему
 */
export const postApplications = <ThrowOnError extends boolean = false>(
  options: Options<PostApplicationsData, ThrowOnError>
) =>
  (options.client ?? client).post<PostApplicationsResponses, PostApplicationsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Отменить заявку
 *
 * Студент отзывает свою заявку (CRUD DELETE)
 */
export const deleteApplicationsByAppId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApplicationsByAppIdData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteApplicationsByAppIdResponses, DeleteApplicationsByAppIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications/{app_id}',
    ...options,
  });

/**
 * Получить детали заявки
 */
export const getApplicationsByAppId = <ThrowOnError extends boolean = false>(
  options: Options<GetApplicationsByAppIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetApplicationsByAppIdResponses, GetApplicationsByAppIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications/{app_id}',
    ...options,
  });

/**
 * Обновить статус заявки
 */
export const patchApplicationsByAppId = <ThrowOnError extends boolean = false>(
  options: Options<PatchApplicationsByAppIdData, ThrowOnError>
) =>
  (options.client ?? client).patch<PatchApplicationsByAppIdResponses, PatchApplicationsByAppIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/applications/{app_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
