// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {});
};

export type UserCreate = {
  email: string;
  password: string;
  role: 'student' | 'teacher';
};

export type UserLogin = {
  username: string;
  password: string;
};

export type Token = {
  access_token?: string;
  token_type?: 'bearer';
};

export type UserResponse = {
  id?: string;
  email?: string;
  role?: 'student' | 'teacher' | 'admin';
  created_at?: string;
};

export type UserUpdate = {
  email?: string;
  role?: 'student' | 'teacher' | 'admin';
};

export type StudentProfile = {
  id?: string;
  user_id?: string;
  first_name?: string;
  last_name?: string;
  readonly student_id_num?: string;
  department_id?: string;
};

export type TeacherProfile = {
  id?: string;
  user_id?: string;
  first_name?: string;
  last_name?: string;
  position?: string;
  department_id?: string;
};

export type ProfileUpdate = {
  first_name?: string;
  last_name?: string;
  department_id?: string;
  position?: string;
};

export type Department = {
  id?: string;
  name?: string;
  code?: string;
  created_at?: string;
};

export type TopicCreate = {
  title: string;
  description: string;
  department_id: string;
  max_students?: number;
};

export type TopicResponse = {
  id?: string;
  teacher_id?: string;
  title?: string;
  description?: string;
  department_id?: string;
  status?: 'open' | 'closed';
  max_students?: number;
};

export type TopicUpdate = {
  title?: string;
  description?: string;
  status?: 'open' | 'closed';
  max_students?: number;
};

export type Skill = {
  id?: string;
  name?: string;
  category?: string;
  code?: string;
};

export type SkillCreate = {
  name: string;
  category?: string;
  code: string;
};

export type UserSkill = {
  id?: string;
  user_id?: string;
  skill_id?: string;
  proficiency?: number;
  evidence_url?: string;
};

export type UserSkillCreate = {
  skill_id: string;
  proficiency?: number;
  evidence_url?: string;
};

export type TopicSkillLink = {
  skill_id: string;
  is_required?: boolean;
};

export type ApplicationCreate = {
  topic_id: string;
  motivation_letter?: string;
};

export type ApplicationResponse = {
  id?: string;
  topic_id?: string;
  user_id?: string;
  status?: 'pending' | 'accepted' | 'rejected';
  motivation_letter?: string;
  created_at?: string;
};

export type ApplicationUpdate = {
  status?: 'pending' | 'accepted' | 'rejected';
};

export type SavedTopic = {
  id?: string;
  student_id?: string;
  topic_id?: string;
  created_at?: string;
};

export type SuccessResponse = {
  status?: string;
};

export type HttpError = {
  detail: string;
};

export type ValidationError = {
  detail?: Array<{
    loc?: Array<string>;
    msg?: string;
    type?: string;
  }>;
};

export type StudentProfileWritable = {
  id?: string;
  user_id?: string;
  first_name?: string;
  last_name?: string;
  department_id?: string;
};

export type PostAuthRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type PostAuthRegisterErrors = {
  /**
   * Неверный ввод
   */
  400: HttpError;
  /**
   * Email уже существует
   */
  409: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
  /**
   * Пользователь создан и авторизован
   */
  201: Token;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type PostAuthLoginErrors = {
  /**
   * Неверный email или пароль
   */
  401: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
  /**
   * Успешный вход
   */
  200: Token;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetUsersMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type GetUsersMeErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Профиль не найден
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
  /**
   * Данные профиля
   */
  200: StudentProfile | TeacherProfile;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PatchUsersMeData = {
  body: ProfileUpdate;
  path?: never;
  query?: never;
  url: '/users/me';
};

export type PatchUsersMeErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Профиль не найден
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PatchUsersMeError = PatchUsersMeErrors[keyof PatchUsersMeErrors];

export type PatchUsersMeResponses = {
  /**
   * Профиль обновлен
   */
  200: StudentProfile | TeacherProfile;
};

export type PatchUsersMeResponse = PatchUsersMeResponses[keyof PatchUsersMeResponses];

export type DeleteUsersByUserIdData = {
  body?: never;
  path: {
    user_id: string;
  };
  query?: never;
  url: '/users/{user_id}';
};

export type DeleteUsersByUserIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Пользователь не найден
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type DeleteUsersByUserIdError = DeleteUsersByUserIdErrors[keyof DeleteUsersByUserIdErrors];

export type DeleteUsersByUserIdResponses = {
  /**
   * Пользователь удален
   */
  200: SuccessResponse;
};

export type DeleteUsersByUserIdResponse = DeleteUsersByUserIdResponses[keyof DeleteUsersByUserIdResponses];

export type GetUsersByUserIdData = {
  body?: never;
  path: {
    user_id: string;
  };
  query?: never;
  url: '/users/{user_id}';
};

export type GetUsersByUserIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Пользователь не найден
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetUsersByUserIdError = GetUsersByUserIdErrors[keyof GetUsersByUserIdErrors];

export type GetUsersByUserIdResponses = {
  /**
   * Данные пользователя
   */
  200: UserResponse;
};

export type GetUsersByUserIdResponse = GetUsersByUserIdResponses[keyof GetUsersByUserIdResponses];

export type PatchUsersByUserIdData = {
  body?: UserUpdate;
  path: {
    user_id: string;
  };
  query?: never;
  url: '/users/{user_id}';
};

export type PatchUsersByUserIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Пользователь не найден
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PatchUsersByUserIdError = PatchUsersByUserIdErrors[keyof PatchUsersByUserIdErrors];

export type PatchUsersByUserIdResponses = {
  /**
   * Пользователь обновлен
   */
  200: UserResponse;
};

export type PatchUsersByUserIdResponse = PatchUsersByUserIdResponses[keyof PatchUsersByUserIdResponses];

export type PatchUsersByUserIdRoleData = {
  body?: {
    role?: 'student' | 'teacher' | 'admin';
  };
  path: {
    user_id: string;
  };
  query?: never;
  url: '/users/{user_id}/role';
};

export type PatchUsersByUserIdRoleErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Пользователь не найден
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PatchUsersByUserIdRoleError = PatchUsersByUserIdRoleErrors[keyof PatchUsersByUserIdRoleErrors];

export type PatchUsersByUserIdRoleResponses = {
  /**
   * Роль обновлена
   */
  200: UserResponse;
};

export type PatchUsersByUserIdRoleResponse = PatchUsersByUserIdRoleResponses[keyof PatchUsersByUserIdRoleResponses];

export type GetDepartmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/departments';
};

export type GetDepartmentsErrors = {
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetDepartmentsError = GetDepartmentsErrors[keyof GetDepartmentsErrors];

export type GetDepartmentsResponses = {
  /**
   * Список кафедр
   */
  200: Array<Department>;
};

export type GetDepartmentsResponse = GetDepartmentsResponses[keyof GetDepartmentsResponses];

export type GetTopicsData = {
  body?: never;
  path?: never;
  query?: {
    department_id?: string;
    status?: 'open' | 'closed';
  };
  url: '/topics';
};

export type GetTopicsErrors = {
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetTopicsError = GetTopicsErrors[keyof GetTopicsErrors];

export type GetTopicsResponses = {
  /**
   * Список тем
   */
  200: Array<TopicResponse>;
};

export type GetTopicsResponse = GetTopicsResponses[keyof GetTopicsResponses];

export type PostTopicsData = {
  body: TopicCreate;
  path?: never;
  query?: never;
  url: '/topics';
};

export type PostTopicsErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Кафедра не найдена
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostTopicsError = PostTopicsErrors[keyof PostTopicsErrors];

export type PostTopicsResponses = {
  /**
   * Тема создана
   */
  201: TopicResponse;
};

export type PostTopicsResponse = PostTopicsResponses[keyof PostTopicsResponses];

export type DeleteTopicsByTopicIdData = {
  body?: never;
  path: {
    topic_id: string;
  };
  query?: never;
  url: '/topics/{topic_id}';
};

export type DeleteTopicsByTopicIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Тема не найдена
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type DeleteTopicsByTopicIdError = DeleteTopicsByTopicIdErrors[keyof DeleteTopicsByTopicIdErrors];

export type DeleteTopicsByTopicIdResponses = {
  /**
   * Тема удалена
   */
  200: SuccessResponse;
};

export type DeleteTopicsByTopicIdResponse = DeleteTopicsByTopicIdResponses[keyof DeleteTopicsByTopicIdResponses];

export type GetTopicsByTopicIdData = {
  body?: never;
  path: {
    topic_id: string;
  };
  query?: never;
  url: '/topics/{topic_id}';
};

export type GetTopicsByTopicIdErrors = {
  /**
   * Тема не найдена
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetTopicsByTopicIdError = GetTopicsByTopicIdErrors[keyof GetTopicsByTopicIdErrors];

export type GetTopicsByTopicIdResponses = {
  /**
   * Детали темы
   */
  200: TopicResponse;
};

export type GetTopicsByTopicIdResponse = GetTopicsByTopicIdResponses[keyof GetTopicsByTopicIdResponses];

export type PatchTopicsByTopicIdData = {
  body?: TopicUpdate;
  path: {
    topic_id: string;
  };
  query?: never;
  url: '/topics/{topic_id}';
};

export type PatchTopicsByTopicIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Тема не найдена
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PatchTopicsByTopicIdError = PatchTopicsByTopicIdErrors[keyof PatchTopicsByTopicIdErrors];

export type PatchTopicsByTopicIdResponses = {
  /**
   * Тема обновлена
   */
  200: TopicResponse;
};

export type PatchTopicsByTopicIdResponse = PatchTopicsByTopicIdResponses[keyof PatchTopicsByTopicIdResponses];

export type DeleteTopicsByTopicIdFavoriteData = {
  body?: never;
  path: {
    topic_id: string;
  };
  query?: never;
  url: '/topics/{topic_id}/favorite';
};

export type DeleteTopicsByTopicIdFavoriteErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Не сохранено
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type DeleteTopicsByTopicIdFavoriteError =
  DeleteTopicsByTopicIdFavoriteErrors[keyof DeleteTopicsByTopicIdFavoriteErrors];

export type DeleteTopicsByTopicIdFavoriteResponses = {
  /**
   * Удалено
   */
  200: SuccessResponse;
};

export type DeleteTopicsByTopicIdFavoriteResponse =
  DeleteTopicsByTopicIdFavoriteResponses[keyof DeleteTopicsByTopicIdFavoriteResponses];

export type PostTopicsByTopicIdFavoriteData = {
  body?: never;
  path: {
    topic_id: string;
  };
  query?: never;
  url: '/topics/{topic_id}/favorite';
};

export type PostTopicsByTopicIdFavoriteErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Тема не найдена
   */
  404: HttpError;
  /**
   * Уже сохранено
   */
  409: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostTopicsByTopicIdFavoriteError =
  PostTopicsByTopicIdFavoriteErrors[keyof PostTopicsByTopicIdFavoriteErrors];

export type PostTopicsByTopicIdFavoriteResponses = {
  /**
   * Добавлено в избранное
   */
  201: SavedTopic;
};

export type PostTopicsByTopicIdFavoriteResponse =
  PostTopicsByTopicIdFavoriteResponses[keyof PostTopicsByTopicIdFavoriteResponses];

export type GetSkillsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/skills';
};

export type GetSkillsErrors = {
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetSkillsError = GetSkillsErrors[keyof GetSkillsErrors];

export type GetSkillsResponses = {
  /**
   * Список навыков
   */
  200: Array<Skill>;
};

export type GetSkillsResponse = GetSkillsResponses[keyof GetSkillsResponses];

export type PostSkillsData = {
  body?: SkillCreate;
  path?: never;
  query?: never;
  url: '/skills';
};

export type PostSkillsErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Навык существует
   */
  409: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostSkillsError = PostSkillsErrors[keyof PostSkillsErrors];

export type PostSkillsResponses = {
  /**
   * Навык создан
   */
  201: Skill;
};

export type PostSkillsResponse = PostSkillsResponses[keyof PostSkillsResponses];

export type DeleteSkillsBySkillIdData = {
  body?: never;
  path: {
    skill_id: string;
  };
  query?: never;
  url: '/skills/{skill_id}';
};

export type DeleteSkillsBySkillIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Не найдено
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type DeleteSkillsBySkillIdError = DeleteSkillsBySkillIdErrors[keyof DeleteSkillsBySkillIdErrors];

export type DeleteSkillsBySkillIdResponses = {
  /**
   * Навык удален
   */
  200: SuccessResponse;
};

export type DeleteSkillsBySkillIdResponse = DeleteSkillsBySkillIdResponses[keyof DeleteSkillsBySkillIdResponses];

export type PatchSkillsBySkillIdData = {
  body?: SkillCreate;
  path: {
    skill_id: string;
  };
  query?: never;
  url: '/skills/{skill_id}';
};

export type PatchSkillsBySkillIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Не найдено
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PatchSkillsBySkillIdError = PatchSkillsBySkillIdErrors[keyof PatchSkillsBySkillIdErrors];

export type PatchSkillsBySkillIdResponses = {
  /**
   * Навык обновлен
   */
  200: Skill;
};

export type PatchSkillsBySkillIdResponse = PatchSkillsBySkillIdResponses[keyof PatchSkillsBySkillIdResponses];

export type GetUsersMeSkillsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/me/skills';
};

export type GetUsersMeSkillsErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetUsersMeSkillsError = GetUsersMeSkillsErrors[keyof GetUsersMeSkillsErrors];

export type GetUsersMeSkillsResponses = {
  /**
   * Список навыков пользователя
   */
  200: Array<UserSkill>;
};

export type GetUsersMeSkillsResponse = GetUsersMeSkillsResponses[keyof GetUsersMeSkillsResponses];

export type PostUsersMeSkillsData = {
  body?: UserSkillCreate;
  path?: never;
  query?: never;
  url: '/users/me/skills';
};

export type PostUsersMeSkillsErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Навык не найден
   */
  404: HttpError;
  /**
   * Навык уже добавлен
   */
  409: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostUsersMeSkillsError = PostUsersMeSkillsErrors[keyof PostUsersMeSkillsErrors];

export type PostUsersMeSkillsResponses = {
  /**
   * Навык добавлен
   */
  201: UserSkill;
};

export type PostUsersMeSkillsResponse = PostUsersMeSkillsResponses[keyof PostUsersMeSkillsResponses];

export type PostTopicsByTopicIdSkillsData = {
  body?: TopicSkillLink;
  path: {
    topic_id: string;
  };
  query?: never;
  url: '/topics/{topic_id}/skills';
};

export type PostTopicsByTopicIdSkillsErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Тема/Навык не найден
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostTopicsByTopicIdSkillsError = PostTopicsByTopicIdSkillsErrors[keyof PostTopicsByTopicIdSkillsErrors];

export type PostTopicsByTopicIdSkillsResponses = {
  /**
   * Навык связан
   */
  201: TopicSkillLink;
};

export type PostTopicsByTopicIdSkillsResponse =
  PostTopicsByTopicIdSkillsResponses[keyof PostTopicsByTopicIdSkillsResponses];

export type GetApplicationsData = {
  body?: never;
  path?: never;
  query?: {
    status?: 'pending' | 'accepted' | 'rejected';
  };
  url: '/applications';
};

export type GetApplicationsErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetApplicationsError = GetApplicationsErrors[keyof GetApplicationsErrors];

export type GetApplicationsResponses = {
  /**
   * Список заявок
   */
  200: Array<ApplicationResponse>;
};

export type GetApplicationsResponse = GetApplicationsResponses[keyof GetApplicationsResponses];

export type PostApplicationsData = {
  body: ApplicationCreate;
  path?: never;
  query?: never;
  url: '/applications';
};

export type PostApplicationsErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Тема закрыта
   */
  403: HttpError;
  /**
   * Тема не найдена
   */
  404: HttpError;
  /**
   * Уже подана заявка
   */
  409: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PostApplicationsError = PostApplicationsErrors[keyof PostApplicationsErrors];

export type PostApplicationsResponses = {
  /**
   * Заявка отправлена
   */
  201: ApplicationResponse;
};

export type PostApplicationsResponse = PostApplicationsResponses[keyof PostApplicationsResponses];

export type DeleteApplicationsByAppIdData = {
  body?: never;
  path: {
    app_id: string;
  };
  query?: never;
  url: '/applications/{app_id}';
};

export type DeleteApplicationsByAppIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Заявка не найдена
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type DeleteApplicationsByAppIdError = DeleteApplicationsByAppIdErrors[keyof DeleteApplicationsByAppIdErrors];

export type DeleteApplicationsByAppIdResponses = {
  /**
   * Заявка удалена
   */
  200: SuccessResponse;
};

export type DeleteApplicationsByAppIdResponse =
  DeleteApplicationsByAppIdResponses[keyof DeleteApplicationsByAppIdResponses];

export type GetApplicationsByAppIdData = {
  body?: never;
  path: {
    app_id: string;
  };
  query?: never;
  url: '/applications/{app_id}';
};

export type GetApplicationsByAppIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Заявка не найдена
   */
  404: HttpError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type GetApplicationsByAppIdError = GetApplicationsByAppIdErrors[keyof GetApplicationsByAppIdErrors];

export type GetApplicationsByAppIdResponses = {
  /**
   * Детали заявки
   */
  200: ApplicationResponse;
};

export type GetApplicationsByAppIdResponse = GetApplicationsByAppIdResponses[keyof GetApplicationsByAppIdResponses];

export type PatchApplicationsByAppIdData = {
  body?: ApplicationUpdate;
  path: {
    app_id: string;
  };
  query?: never;
  url: '/applications/{app_id}';
};

export type PatchApplicationsByAppIdErrors = {
  /**
   * Не авторизован
   */
  401: HttpError;
  /**
   * Доступ запрещен
   */
  403: HttpError;
  /**
   * Заявка не найдена
   */
  404: HttpError;
  /**
   * Ошибка валидации
   */
  422: ValidationError;
  /**
   * Внутренняя ошибка сервера
   */
  500: HttpError;
};

export type PatchApplicationsByAppIdError = PatchApplicationsByAppIdErrors[keyof PatchApplicationsByAppIdErrors];

export type PatchApplicationsByAppIdResponses = {
  /**
   * Статус обновлен
   */
  200: ApplicationResponse;
};

export type PatchApplicationsByAppIdResponse =
  PatchApplicationsByAppIdResponses[keyof PatchApplicationsByAppIdResponses];
